trigger: none

pool:
  vmImage: ubuntu-latest

steps:
  - task: UsePythonVersion@0
    displayName: Install Python
    inputs:
      versionSpec: '3.11'
      addToPath: true
      architecture:  x64

# Use Azure CLI to retrieve OAS from APIM
# Replace script parameters with your resource group, APIM service name, and API ID
  - task: AzureCLI@2
    inputs:
      azureSubscription: '<your subscription name'  # Azure Resource Manager service connection selected during task configuration
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az apim api export \
        -g <your-resource-group> \
        --service-name <your-apim-service-name> \
        --api-id <your-api-name> \
        --export-format OpenApiYamlFile \
        --file-path $(Build.Repository.LocalPath)

  - task: APIContractSecurityAudit@5
    displayName: Audit API specifications
    inputs:
      platformServiceConnection: '42Crunch Audit'
      logLevel: 'INFO'
      rootDirectory: '$(Build.Repository.LocalPath)'
      sarifReport: '$(Build.Repository.LocalPath)/$(Build.BuildId)-auditreport.sarif'

  - task: PublishBuildArtifacts@1
    displayName: publishAuditSarif
    inputs:
      PathtoPublish: '$(Build.Repository.LocalPath)/$(Build.BuildId)-auditreport.sarif'
      ArtifactName: 'CodeAnalysisLogs'
      publishLocation: 'Container'

  - task: AdvancedSecurity-Publish@1
    displayName: Publish to Advanced Security
    inputs:
      SarifsInputDirectory: '$(Build.Repository.LocalPath)'
      Category: '42Crunch API Security Audit'
